name: anacondaenv36
channels:
 - defaults
dependencies:
- flask=0.12.2
- dill=0.2.6
- pip:
  - h5py==2.7.0
  - keras==2.0.7
  - numpy>=1.13.0
  - pillow==4.2.1
  - pymongo==3.4.0
  - sklearn==0.0
  - tensorflow==1.3.0
  - theano==0.9.0
  - pandas==0.20.3