name: anacondaenv36
channels:
- defaults
dependencies:
#- click=6.7=py36_0
- dill=0.2.6=py36_0
- flask=0.12.2=py36_0
#- itsdangerous=0.24=py36_0
#- jinja2=2.9.6=py36_0
- markupsafe=0.23=py36_2
#- openssl=1.0.2l=0
#- pip=9.0.1=py36_1
- python=3.6.1=2
#- readline=6.2=2
#- setuptools=27.2.0=py36_0
#- sqlite=3.13.0=0
#- tk=8.5.18=0
#- ujson=1.35=py36_0
#- werkzeug=0.12.2=py36_0
#- wheel=0.29.0=py36_0
#- xz=5.2.2=1
#- zlib=1.2.8=3
- pip:
  - affinegap==1.10
#  - bcolz==1.1.2
#  - beautifulsoup4==4.6.0
#  - bleach==1.5.0
#  - btrees==4.4.1
#  - canonicalize==1.3
#  - categorical-distance==1.9
#  - certifi==2017.4.17
#  - chardet==3.0.4
#  - cssselect==1.0.1
#  - datetime-distance==0.1.2
#  - dedupe==1.6.15
#  - dedupe-hcluster==0.3.2
#  - dedupe-variable-datetime==0.1.2
#  - doublemetaphone==0.1
#  - fastcluster==1.1.23
#  - feedfinder2==0.0.4
#  - feedparser==5.2.1
#  - future==0.16.0
  - h5py==2.7.0
#  - haversine==0.4.5
#  - highered==0.2.1
#  - html5lib==0.9999999
#  - idna==2.5
#  - jellyfish==0.5.1
#  - jieba3k==0.35.1
  - keras==2.0.7
#  - levenshtein-search==1.4.4
#  - lxml==3.8.0
#  - markdown==2.6.9
#  - newspaper3k==0.2.2
#  - nltk==3.2.4
  - numpy==1.13.0
#  - olefile==0.44
  - pandas==0.20.3
#  - pbr==3.0.1
#  - persistent==4.2.4.2
  - pillow==4.2.1
#  - probableparsing==0.0.1
#  - protobuf==3.4.0
#  - pyhacrf-datamade==0.2.1
#  - pylbfgs==0.2.0.5
#  - pymongo==3.4.0
#  - python-crfsuite==0.9.2
#  - python-dateutil==2.6.0
#  - pytz==2017.2
#  - pyyaml==3.12
#  - requests==2.18.1
#  - requests-file==1.4.2
#  - rlr==2.4.3
#  - scikit-learn==0.19.0
#  - scipy==0.19.1
#  - simplecosine==1.1
#  - simplejson==3.10.0
#  - six==1.10.0
#  - sklearn==0.0
#  - stevedore==1.23.0
  - tensorflow==1.3.0
  - theano==0.9.0
#  - tldextract==2.1.0
#  - urllib3==1.21.1
#  - us==0.9.1
#  - usaddress==0.5.10
#  - virtualenv==15.1.0
#  - virtualenv-clone==0.2.6
#  - virtualenvwrapper==4.7.2
#  - zope.index==4.3.0
#  - zope.interface==4.4.1